### ISSUE TITLE
Add configuration for excorcist for external source map file 

### ISSUE THREAD

**Issue by michaelBenin** [jmreidy/grunt-browserify#132]
https://npmjs.org/package/exorcist

the external file can be used with services such as rollbar in production

**Comment by atdiff** [comment]
@michaelBenin were you able to get this to work using exorcist in your transform?

**Comment by michaelBenin** [comment]
I ended up with this: https://github.com/michaelBenin/node-startup/blob/develop/automation/extract_sourcemap.js which extracted the source maps after.
