### ISSUE TITLE
Sourcemaps not being created -- 

### ISSUE THREAD

**Issue by andrew-luhring** [jmreidy/grunt-browserify#162]
Firstly I'm aware that [this has been addressed](https://github.com/jmreidy/grunt-browserify/issues/161) before; the difference is, his error was coffeescript related mine isn't:

``` js

var config =    {
        browserify: {
                       client: {
                    src: JS_DIR + "script.js"
                ,   dest: BUNDLE_DIR+ "bundle.js"
                }
                        ,   test: {
                    src: TEST_DIR + "_script.js"
                ,   dest: BUNDLE_DIR + "_bundle.js"
                }
            ,   options: {
                    debug: true
                }
            }
       };


grunt.initConfig( config );
grunt.loadNpmTasks('grunt-browserify');

```

Why are sourcemaps not being generated? I'm assuming this is an error but the docs make no mention of debug or sourcemaps so...

**Comment by dotnetwise** [comment]
hm, I'm getting the same error, but `bundleOptions` seems deprecated and `debug: true` does nothing helpful

**Comment by tleunen** [comment]
Uses `browserifyOptions` instead.
```
browserifyOptions : {
    debug: true
},
```

**Comment by f03lipe** [comment]
Not working for me, @tleunen. :(
May I know which version of browserify and grunt-browserify you're using?

**Comment by tleunen** [comment]
Paste you browserify configuration please. Maybe you didn't put the `browserifyOptions` at the right place.

**Comment by pcruz7** [comment]
@tleunen I can't seem to generate the sourcemaps either. My current version of grunt-browserify is: 2.1.4 and browserify is: 11.0.1. I'm using the following configuration:

```
app: {
            src:  ['public/js/app.js'],
            dest: '.build/js/app.js',

            options: {
                watch:     true,
                keepAlive: true,
                external:  [
                    'react',
                    'react-router',
                    'reflux',
                    'classnames'
                ],

                browserifyOptions: {
                   debug:     true, 
                   extensions: ['.jsx']
                },

                transform: ['babelify', 'aliasify']
            }
        }
```

**Comment by tleunen** [comment]
Update `grunt-browserify` and try again. If the problem persists, please create a new ticket.

**Comment by pcruz7** [comment]
That solved it @tleunen. Many thanks !
