### ISSUE TITLE
options.standalone does not work in 2.x

### ISSUE THREAD

**Issue by thanpolas** [jmreidy/grunt-browserify#165]
the `standalone` option will not work on 2.0.1, i reverted to 1.3.2 and it works just fine.

**Comment by hypesystem** [comment]
To anyone wondering, `standalone` is now an argument in `browserifyOptions`.

**Comment by pathogen-** [comment]
I found this issue when searching to solve the same problem.

This is what worked for me:

    browserify:
        src: ['<%= pkg.name %>.js']
        dest: './browser/dist/<%= pkg.name %>.standalone.js'
        options:
          browserifyOptions:
            standalone: '<%= pkg.name %>'
