### ISSUE TITLE
Transform usage unclear with new browserify-shim setup

### ISSUE THREAD

**Issue by jkymarsh** [jmreidy/grunt-browserify#181]
I'm not entirely sure if this falls more within the realm of a `grunt-browserify` or `browserify-shim` issue. Figured I'd toss it here first to see if you guys had any insight.

As far as I understand, the proper usage of `browserify-shim`, now that it's been removed from `grunt-browserify`, is to install via npm and then include as a transform, as such:

    grunt.initConfig({
        browserify: {
            libs: {
                src: ['./bower_components/angular/angular.js'],
                dest: './public/js/built/libs.js',
                options: {
                    transform: ['browserify-shim']
                }
            }
        }
    });

However, it's completely unclear to me as to how to utilize config within `browserify-shim` then... It appears that they've moved to a model where all config is stored in `package.json`, and this is confirmed when attempting to run this task and getting:

    Error: unable to find a browserify-shim config section in the package.json for...

And adding the config sections to `package.json`, while it gets rid of the error, doesn't seem to actually work during the `grunt-browserify` build.

I think it'd be great to include a little more detail/documentation on how to use transforms like the shim, especially given how fast the modules are changing. I feel like I'm shooting in the dark with no documentation at all to go off.

**Comment by eschwartz** [comment]
Can we please add some documentation on this to the README (eg. "grunt-browserify is not compatible with the browserify-shim transform"). This caused me major headaches, trying to figure out what was wrong in my code.

**Comment by tleunen** [comment]
Is it really not compatible? I'm using it in a project (but with an old version of `grunt-browserify` and it works). The only thing I think is that you have to specify `browserify-shim` inside your package.json:
```
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "./src/lib/modernizr.custom.js": "Modernizr",
  },
```
So yes, if this is really needed, we should add a special comment in the readme for `browserify-shim`.

**Comment by eschwartz** [comment]
From following this thread, and from my experience, it looks like it is really not compatible - the browserify shim is working if I run browserify from the command line, but not with the browserify-shim grunt task.

Are you using browserify-shim v3? If you're getting it to work with v3, than the problem may be more specific.

**Comment by tleunen** [comment]
I'm using `browserify-shim 3.8.2` and `grunt-browserify 3.2.1` for a project and the config I gave above is working for me. I can't test the same project with a more recent build of grunt browserify
