### ISSUE TITLE
how to achieve aliasMapping?

### ISSUE THREAD

**Issue by mikepuerto** [jmreidy/grunt-browserify#190]
Since aliasMapping is deprecated, how does one make an "alias" for a directory? For example, previously you could do the following: 

```
{
  app: {
    src: [ 
      'app/**/*.js' 
    ],
      dest: 'public/site.js'
    },
    options: {
      aliasMappings: [{
        cwd: 'app/',
        src: [ '**/*.js' ],
        dest: 'app/'
      }]
    }
  }
}
```

now with aliasMappings gone, when I try to build I get errors like **>> Error: module "app/router" not found from** - What is the correct way to do this in the latest version of grunt-browserify?

**Comment by mikepuerto** [comment]
@kacinskas I need to upgrade browserfiy at this point... I've tried your solution but I'm getting:
```bash
>> Error: write after end
Warning: Error running grunt-browserify. Use --force to continue.
```
any ideas why this might happen?

**Comment by joeybaker** [comment]
@mikepuerto this is a problem with remapify and Browserify >7. I'm working on a fix https://github.com/joeybaker/remapify/issues/24

**Comment by kacinskas** [comment]
@mikepuerto I had to fix on package versions.
Im now on old versions of browserify@6.3.3 and remapify@1.3.0
I did not tryied what last working versions are, so cant advice, probably - Browserify >7 and remapify>1.4.3

**Comment by mikepuerto** [comment]
@kacinskas what version of grunt-browserify are you using? I tried downgrading the packages to the versions you mentioned above but grunt-browserify is apparently still using browserify 8 internally.

Thanks!

**Comment by mikepuerto** [comment]
@kacinskas I actually went back to v3.2.1 and it seems better... still running into issues though(too many open files), would you mind sharing one of your target config sections?

**Comment by kacinskas** [comment]
@mikepuerto yes grunt-browserify@3.2.1
regarding "too many open files" - is from your system's ulimit open files setting, https://github.com/gruntjs/grunt-contrib-watch see FAQ
