### ISSUE TITLE
Change alias implementation

### ISSUE THREAD

**Issue by foxx** [jmreidy/grunt-browserify#210]
Currently aliases require to be configured like so;

```
alias: [
    'vendor/jquery-1.11.0.js:jquery',
    'vendor/module1.js:module1',
]
```

Could we not have a more friendly implementation? Such as;

```
alias: {
    "jquery" : "vendor/jquery-1.11.0.js",
    "module2" : "vendor/module2.js",
}
```

This keeps the alias definitions as a real object and also doubles up as being easier on the eyes. 

Backwards compatibility wouldn't be an issue, you could handle the parsing based on the value type, but would modify the docs so that users moving forward are using the newer approach. Then on the next major version number, depreciate the old method perhaps.

Looks like this would be fairly easy to do, happy to send a PR if you'd be happy to accept this design change.

Thoughts?

**Comment by tleunen** [comment]
I like this idea. It's a lot easier to see the alias with this approach. I'm gonna add this way of adding aliases and update the readme.
