### ISSUE TITLE
Add a warning when people try to use aliasMappings

### ISSUE THREAD

**Issue by srcspider** [jmreidy/grunt-browserify#213]
Every single source on the internet tells you that's how to do it and there's no feedback that you're not suppose to use it. 

So that it's not just a fix for this option you can just implement it as "show warning when trying to use unsupported functionality" where unsupported is anything you don't recognize.

-

This would save people (like myself) a good hour debugging. And yes I have looked into the docs, but dismissed it not being there as "poor documentation," or as me doing it wrong (since the task only claimed I'm using it wrong in my js not the task itself). 

It currently shows in the changelog in the source of the module but nothing about removing it shows up; albeit I do see how it's a comment inside a section in the readme that seemed unrelated the first time I read it.

**Comment by tleunen** [comment]
The solution on this thread is valid, but it would be better to use [joeybaker/remapify](https://github.com/joeybaker/remapify).
