### ISSUE TITLE
Can't get standalone to work

### ISSUE THREAD

**Issue by 0x80** [jmreidy/grunt-browserify#232]
Somehow I can't get standalone to work from grunt. If I do this on the cli it works fine:

    browserify -x jquery -x lodash -x async -s ZN.mymodule mymodule/*.js > public/javascripts/mymodule.js

I would expect this to be the equivalent using grunt:

    mymodule: {
        src: ['mymodule/**/*.js'],
        dest: 'public/javascripts/mymodule.js',
        options: {
          external: ['jquery', 'async', 'lodash'],
          standalone: 'ZN.mymodule'
        }
   }

But instead my browser complains: 'Uncaught ReferenceError: ZN is not defined'

What am I missing here?

**Comment by tleunen** [comment]
Maybe for `grunt-browserify` v4 :)
