### ISSUE TITLE
How to avoid full system paths appearing in bundled code?

### ISSUE THREAD

**Issue by callumlocke** [jmreidy/grunt-browserify#237]
When I bundle using grunt-browserify, the bundle contains full absolute paths to every module used, revealing my local username and a worrying amount of info about how I organise my stuff on my computer. (And this info is in strings so it survives minification.)

I've tried using browserify's basedir option to force it to use relative paths, but I can't get it to work.

``` js
        browserify: {
            main: {
                src: ['<%= config.app %>/scripts/main.js'],
                dest: '.tmp/scripts/main-bundle.js',
                options: {
                    watch: true,
                    debug: true,
                    transform: ['debowerify', 'hbsfy'],
                    browserifyOptions: {
                        basedir: './'
                    }
                }
            }
        },
```

Am I using this wrong?

**Comment by tydaeus** [comment]
Current browserify defaults fullPaths to false, grunt-browserify does not. This seems inconsistent.

**Comment by tleunen** [comment]
fullPath is only true when watch is true.
