### ISSUE TITLE
Transforms not applied when `src` is empty

### ISSUE THREAD

**Issue by dominykas** [jmreidy/grunt-browserify#239]
Never ran into this until upgrade to 3.x: I'm exposing all modules via `alias` and so I used to keep `src` empty. As of 3.x, this prevents transforms (and other options?).

Workaround (correct way of doing things?) is to have at least one file in `src`, even if it is exposed via `alias` - this magically makes transforms work again.

**Comment by tleunen** [comment]
Cannot reproduce this issue using the latest version
