### ISSUE TITLE
watch true + remapify throws fatal error on bundle update

### ISSUE THREAD

**Issue by matthieugayon** [jmreidy/grunt-browserify#244]
Hi there, 

I'm having problems when using watchify and the preBundleCB hook ( within remapify plugin  for remapping modules paths) :

Here is my browserify config : 

```javascript
watch: {
            scripts: {
                files: 'app/**/*.js'
            },
        },
        browserify: {
            app: {
                options: {
                    watch: true,
                    require: Object.keys(pjson.browser),
                    preBundleCB: function(b) {
                        b.plugin(remapify, {
                            cwd: './app',
                            src: '**/*.js',
                            expose: 'app'
                        });
                        b.on('remapify:files', function(file, expandedAliases) {
                            Object.keys(expandedAliases).forEach(function(key) {
                                if (key.indexOf('.js') === -1) {
                                    b.require(expandedAliases[key], {expose: key, detectGlobals : false});
                                }
                            });
                        });
                    }
                },
                files: {
                    'public/app.js': ['app/**/*.js']
                }
            }
        }
```

After running "grunt browserify watch", everytime I make a change in one of my files located in the app directory ( those files are being watched by watchify to run the watchify optimized bundle recompilation, and our watch task reload the whole grunt process ) I get this error : 

```
>> File "app/views/app_view.js" changed.
Completed in 0.001s at Wed Oct 01 2014 10:45:42 GMT+0200 (CEST) - Waiting...
>> /Users/me/Documents/app/views/app_view.js changed, updating browserify bundle.
>> Watchifying...
Fatal error: write after end
```

It looks like there's a problem with watchify bundle update and the way I'm remapifying my modules paths, 
any idea ?

**Comment by roncli** [comment]
The issue is remapify's plugin is asynchronous, but `preBundleCB` expects a synchronous function.  joeybaker/remapify#26 is a potential update remapify to make it synchronous.

Perhaps `preBundleCB` could be setup to be asynchronous to avoid problems like this?  Or maybe create an asynchronous version of it?

**Comment by tleunen** [comment]
You can use remapify without using preBundleCB... I don't know why the example is using the preBundleCB.
```
plugin: [
    [remapify, [
        {
            src: '*.js',
            expose: 'views',
            cwd: './src/views/'
        }
]]
```

**Comment by roncli** [comment]
This is true if all you're doing is transforming the files with remapify.  However, my `preBundleCB` handler does more than just call the plugin to do the transforming, it also runs `b.require()` on the files exposing them under the aliases remapify provides.

Also, I've learned that I will need to switch the `b.plugin()` call to come after the event handler, assuming remapify goes synchronous.  So, even then I will still need to call `b.plugin()` inside `preBundleCB` since the `plugin` option runs prior to `preBundleCB`.

From my gruntfile:

```
        browserify: {
            combine_main_js_files: {
                options: {
                    require: Object.keys(pjson.browser),
                    preBundleCB: function(b) {
                        b.on("remapify:files", function(file, expandedAliases) {
                            Object.keys(expandedAliases).forEach(function(key) {
                                if (key.indexOf(".js") === -1 && key.indexOf("\\") === -1) {
                                    b.require(expandedAliases[key], {expose: key});
                                }
                            });
                        });
                        b.plugin(remapify, {
                            cwd: "./app",
                            src: "**/*.js",
                            expose: "app"
                        });
                    }
                },
                files: {
                    "assets/js/site.js": ["app/**/*.js"]
                }
            }
        },
```
