### ISSUE TITLE
How to use the module stringify?

### ISSUE THREAD

**Issue by dotnetwise** [jmreidy/grunt-browserify#250]
https://www.npmjs.org/package/stringify

**Comment by piascikj** [comment]
I'm using stringify for some .md files and got it working like this.

```javascript
      options: {
        transform: [
          function(file) {
            return stringify({extensions: ['.md']}).call(stringify, file);
          }
        ]
      }
```

But looking at the source code, this will only work if process.env.NODE_ENV is not set.

**Comment by boris-marinov** [comment]
FYI The author of browserify has written [a transformation for inlining strings in your code](https://github.com/substack/brfs). 

[Here](http://stackoverflow.com/questions/17379891/how-to-require-text-files-with-browserify/17502924#17502924) he speaks about the benefits of using this transformation VS requiring string.
