### ISSUE TITLE
Multiword option in browserifyOptions

### ISSUE THREAD

**Issue by mgoldWork** [jmreidy/grunt-browserify#258]
I have this shell command
````shell
browserify path/to/src.js --external "*foo*" --no-bundle-external -o path/to/dest.js
````
I've tried exclude, ignore, and external without `--no-bundle-external` and none of them will ignore the foo package requires by src. My grunt target is
````js
myModule: {
        src: 'path/to/src.js',
        dest: 'path/to/dest.js',
        options: { external: ["*foo*"],
                   browserifyOptions: { "no-bundle-external": true }
        }
}
````
This does not work (it bundles foo). My guess is that I am not passing the no-bundle-external flag in a way that gets parsed. I've tried underscores as well. I can pass `debug: true` and that shows up. Any help?

**Comment by taktran** [comment]
Looking at the [docs for browserify](https://github.com/substack/node-browserify#var-b--browserifyfiles-or-opts), it seems like some of the command line options work a bit differently.

I got `--no-bundle-external` to work with `opts.bundleExternal: false` ie,

    browserify: {
      dist: {
        files: { /* ... */ },
        options: {
          browserifyOptions: {
            bundleExternal: false,
          }
        }
      }
    },
```

**Comment by jasonswearingen** [comment]
@taktran, thanks will try that
