### ISSUE TITLE
Cannot get the extension option to work

### ISSUE THREAD

**Issue by jdreux** [jmreidy/grunt-browserify#260]
I've tried the following:

   browserify: {
      browserifyOptions: {
        extension: 'cjsx'
      },
      src: ['.tmp/jsx/{,*/}*.cjsx'],
      dest: '.tmp/scripts/app.js'
    }

Doesn't seem to do anything. Am I doing it right? Would be nice to add an example of the options hash in the doc.

**Comment by marcbachmann** [comment]
Here's a more detailed configuration:
```
browserify: {
  options: {
    transform: ['coffeeify'],
    browserifyOptions: {
      extension: ['.js', '.json', '.coffee']
    }
  },
  dist: {
    files: {
      'dist/app.js' : 'src/app.coffee'
    }
  }
}

```
