### ISSUE TITLE
No error stack on Typescript compilation

### ISSUE THREAD

**Issue by pocesar** [jmreidy/grunt-browserify#265]
Closely related to #106, I'm using grunt-browserify with tsify browserify plugin (cross posting to smrq/tsify#21). The line in `runner.js` that reads:

``` js
    b.on('error', function (err) {
      self.logger.fail.warn(err);
    });
```

halts the task at the first error, which isn't a problem, but the error is being shown as:

```
Warning: Type '{ value: number[]; }' is not assignable to type 'IScore':
  Types of property 'value' are incompatible:
    Type 'number[]' is not assignable to type 'number'. Use --force to continue.
```

the error emitted by tsify is richer than that, it has the following structure:

```
 { [TS2322: Type '{ value: number[]; }' is not assignable to type 'IScore':
   Types of property 'value' are incompatible:
     Type 'number[]' is not assignable to type 'number'.]
   fileName: 'src/client/sections/resultados.ts',
   line: 384,
   column: 33,
   name: 'TS2322',
   message: 'Type \'{ value: number[]; }\' is not assignable to type \'IScore\':\r\n  Types of property \'value\' are incompatible:\r\n    Type \'number[]\' is not assignable to type \'number\'.' } }
```

a typical typescript compiler error shows up like this:

```
### Fast Compile >>src/server/app.ts
### Fast Compile >>src/server/formulas.ts
Using tsc v1.3.0
src/server/formulas.ts(461,107): error TS2345: Argument of type '{ value?: number; relevancia?: number; }' is not assignable to parameter of type 'number'.
```

the error should be changed on tsify plugin or on the browserify plugin? Using --stack or --debug doesn't show anything different

Offtopic: shouldn't the error be handled with `self.logger.fail.fatal` instead?

**Comment by flyon** [comment]
+1 . I too am using TSify with the preBundleCB option. And right now I am stuck because I get a very general error without any information where the problem might be.

**Comment by tleunen** [comment]
Do you still have the issue? If so can I get an example project to work on?
