### ISSUE TITLE
Configuration is wrongly transformed

### ISSUE THREAD

**Issue by checat** [jmreidy/grunt-browserify#266]
First, the correct configuration

```
  grunt.initConfig({
    browserify: {
      options: {
        alias: ['./something.js:some-alias']
      },
      'dist/dist.js': ['some-alias']
    }
  });
```

It is equivalent to `browserify -r ./something.js:some-alias -o dist/dist.js` and gives the same output.

But if a user uses following config that looks logically equivalent:

```
  grunt.initConfig({
    browserify: {
      options: {
        alias: ['./something.js:some-alias']
      },
      'dist/dist.js': ['./something.js']
    }
  });
```
Then the result will be slightly different (still working) on Linux, but on Windows the result will not expose the alias, see https://gist.github.com/checat/5bd0ca2437fc31098640

grunt-browserify should either deny the second config sample or treat it the same way as the first.

grunt@0.4.5, grunt-browserify@3.2.1, browserify@6.3.3

**Comment by tleunen** [comment]
There's a big difference between the 2.
Your first configuration is correct. The equivalent CLI command is this one:
`browserify -r ./something.js:some-alias -o dist/dist.js`

But your second configuration is equivalent to this one:
`browserify ./something.js -r ./something.js:some-alias -o dist/dist.js`

And in that case, you'll get the same output.
