### ISSUE TITLE
move browserify as peerDependency?

### ISSUE THREAD

**Issue by pocesar** [jmreidy/grunt-browserify#268]
The new 7.0 was released some days ago, but grunt-browserify is using 6.x, maybe list it as a peerDependency?

**Comment by tleunen** [comment]
Why not move it as a peer again with a condition like this: `>= 6.0.0 < 9`
(Note sure about the lower version)

**Comment by jmreidy** [comment]
So it looks like I pulled the peer dep (see [here](https://github.com/jmreidy/grunt-browserify/commit/90beb7bba9786eb84f9223b05b0f6c256c70cf66) back when it appeared that peer deps were going to be deprecated in NPM. Which NPM is still considering: https://github.com/npm/npm/issues/5080

**Comment by tleunen** [comment]
In this case I think we could put it back... This will prevent a project from getting multiple browserify versions (see http://blog.nodejs.org/2013/02/07/peer-dependencies/)

**Comment by jmreidy** [comment]
Yeah it can always be pulled again if NPM deprecates it. I'd say that the minimum version in the range should match the most recent major version release though. (So in this case 7.0.0)
