### ISSUE TITLE
external option not working?

### ISSUE THREAD

**Issue by DylanPiercey** [jmreidy/grunt-browserify#269]
For some reason I cannot get 'react' to be external.

Here is my config:

```JavaScript
        browserify: {
            dist: {
                files: {
                    'client/plublic/bundle.js': 'client/code/app.js'
                },
                options: {
                    external: ['react']
                }
            }
        },
```

**Comment by bhonnegowda** [comment]
external does not seem to be working either.
Ex: 	browserify:{
			vendor: {
				files:{
					'build/js/app.js':['client/src/*.js']	
				},
				options:{
					browserifyOptions:{
						debug:true
					},
					transform: ['browserify-shim'],
					external: ['jquery', 'Highcharts', 'Date']
				}
			},
	}

package.json:
"browser": {
    "jquery": "./bower_components/jquery/dist/jquery.js",
    "Highcharts": "./bower_components/highcharts/highcharts.js",
    "datejs": "./bower_components/datejs/build/date.js"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "jquery": "$",
    "Highcharts" :"Highcharts",
    "datejs": "Date"
  },

**Comment by tleunen** [comment]
Yes it should work.
But because the initial issue seems fixed. I'll close this thread.
