### ISSUE TITLE
Alias no longer working

### ISSUE THREAD

**Issue by marcboscher** [jmreidy/grunt-browserify#270]
It seems aliasing causes an error at runtime

`alias : ['lodash:foobar']`
Error: Cannot find module 'foobar'

But this works
`alias : ['lodash:lodash']`

And if I try to alias an internal module
`alias : ['./lib/conf:myconf']`
the build passes, but the output file has 
`/* code of a module using lib/conf */
},{"../conf":undefined}]`
So when the output is actually used, get 
Uncaught Error: Cannot find module './conf'

Could this be related to #236 ?

PS: really confused with alias, require, remapify

**Comment by marcboscher** [comment]
This has been fixed in browserify (tested in 8.0.3). 

Could you please make a release with the updated dependency.

Tks!

Ref: https://github.com/substack/node-browserify/issues/1020

**Comment by tleunen** [comment]
Published as 3.3.0
