### ISSUE TITLE
PSA - don't list the same file in "src" and "options.alias"

### ISSUE THREAD

**Issue by jonknapp** [jmreidy/grunt-browserify#271]
I've been hardcoding projects at version `2.1.4` for awhile as it seemed to break my projects and requires that utilized aliases would fail.  Figured this was due to `browserify` and `watchify` versions changing, but I never knew what the real problem was.

Tried again today to upgrade to the latest `grunt-browserify` version, and after poking and prodding for a few hours I found out that a file **should not** be listed in both the `src` and `options.alias` array.  If it is, compilation will work successfully, but you won't be able to require the alias in your application.  The file should only be listed in `options.alias` and it will be required as a source file automatically.

I hope this helps someone else.  Not sure where it would go (or if it's needed) in the documentation, so I made the issue so that Google can help out frustrated folks like myself.

**Comment by ericcecchi** [comment]
Of course I find this issue after struggling for hours and finally tracking down the issue myself. I also created a solution/workaround in PR #278.
