### ISSUE TITLE
config can't be used as alias

### ISSUE THREAD

**Issue by standup75** [jmreidy/grunt-browserify#275]
Took me a while to realize that this alias would not work (the file does not get included in the destination):

    "./app/conf.coffee:config"

But this works

    "./app/conf.coffee:conf"

**Comment by tleunen** [comment]
I don't have any issue adding an alias with `config` and adding it in the final bundle... I'm not using CoffeeScript though, and using the latest version of `grunt-browserify`.

**Comment by tleunen** [comment]
Tested and I cannot reproduce the issue with the latest build.
