### ISSUE TITLE
Local Npm module "brfs" not found. Is it installed?

### ISSUE THREAD

**Issue by davestewart** [jmreidy/grunt-browserify#276]
Hi there,

Sorry - new to this grunt / browserify thing, but I can't seem to get this transform to work.

My gruntfile is set up like this:

    browserify: {
        dist: {
            files: {
                '<%= options.assets %>/javascripts/bundle.js': ["../src/js/**/*.js", "!../src/js/spec/**/*.js"]
            },
            options: {
                transform: ['../build/brfs'],
                browserifyOptions: {
                    debug: true
                }
            }
        }
    },

I've also installed the brfs module, and I'm loading it using loadNpmTask(). 

And I get the following error:

    $ /usr/local/bin/grunt --gruntfile /Users/davestewart/dev/food-portal/build/Gruntfile.js dev
    >> Local Npm module "brfs" not found. Is it installed?
    
    Running "browserify:dist" (browserify) task
    >> Error: Cannot find module 'brfs' from '/Users/davestewart/dev/food-portal/src/js'
    Warning: Error running grunt-browserify. Use --force to continue.
    
    Aborted due to warnings.
    Process finished with exit code 6

Sorry if this is a dumb question, or I'm missing the basics on this one. I've been googling left right and center but can't seem to put the pieces together.

Cheers,
Dave

**Comment by davestewart** [comment]
OK, think I've got this:

    // at top of grunt file
    var brfs = require('brfs');
    
    // in browserify.options
    transform: [brfs],
    browserifyOptions: {
        debug: true
    }

As I said, I don't know grunt well enough to know if this is "Page 1" stuff or not, but might be worth adding this to your docs as a function example?

Thanks.

**Comment by tleunen** [comment]
You have 2 ways of doing it. A transform can be specified by its name, or by the module itself.
What you did is giving the module itself to `grunt-browserify`. When you do that, you need to require the module before using it (so the need of `require('brfs')`.
What you can do instead is specifying the transform by its name (the same name as the module actually). So you could do this (without the require):
```
transform: ['brfs'],
browserifyOptions: {
    debug: true
}
```
Feel free to send a PR with an example with a specific transform if you feel it's necessary.
