### ISSUE TITLE
Browserify and Watchify Dependencies Out of Date

### ISSUE THREAD

**Issue by elsbree** [jmreidy/grunt-browserify#277]
I've been running into [this](https://github.com/rackt/react-router/issues/442) error using grunt-browserify, due to the fact that watchify is out of date. I did a quick-and-dirty test in my local environment, and updating to the latest versions of browserify and watchify fixed the issue and didn't appear to break anything (all tests passed and the error I was experiencing disappeared). If there are no objections, I'm happy to submit a PR.

**Comment by tleunen** [comment]
`grunt-browserify` has been updated and published as v3.3.0
