### ISSUE TITLE
Task-level browserifyOptions are not merged into target-level options

### ISSUE THREAD

**Issue by burtyish** [jmreidy/grunt-browserify#280]
Seems like the options in the task-level browserifyOptions don't apply on the target level.

I expect this configuration to work, but I got an error message saying that modules weren't found:
```javascript
options: {
    browserifyOptions: {
      extensions: ['.coffee', '.cjsx']
    },
    transform: ['coffee-reactify']
  },
dev: {
    options: {
      browserifyOptions: {
        debug: true
      }
    },
    src: ['<%= config.app %>/scripts/main.coffee'],
    dest: '<%= config.tmp %>/app.js'
  }
```
I finally found that if I move the browserifyOption `extensions` into the target it works fine:
```javascript
options: {
    transform: ['coffee-reactify']
  },
dev: {
    options: {
      browserifyOptions: {
        extensions: ['.coffee', '.cjsx']
        debug: true
      }
    },
    src: ['<%= config.app %>/scripts/main.coffee'],
    dest: '<%= config.tmp %>/app.js'
  }
```
Maybe global options are merged into target options using a shallow merge?

(using ver. 3.2.1)

**Comment by paulmelnikow** [comment]
As you observe, Grunt makes a shallow copy of the target's `options`. That means if a target overrides task-level `browserifyOptions`, it overrides all of it.

https://github.com/gruntjs/grunt/blob/d47c75543b09218be95869eed4c285d6044b538b/lib/grunt/task.js#L69
https://lodash.com/docs#assign

**Comment by burtyish** [comment]
I see. So this behavior is a result of using (the same) parameter with an object-type value. 
Barring a change in grunt, one possible fix  would be having different names for the task and target-level parameters. Like `browserifyOptions` and `targetBrowserifyOptions`. 
Anyway, documenting this limitation may save people a lot of time and frustration.

**Comment by tleunen** [comment]
I was thinking of removing `browserifyOptions` and `watchifyOptions` and put everything at the root of `options` and based on the option name, we could forward the options to browserify/watchify...
But I'm not sure it would be a good idea :)
Anyway, I agree documenting this limitation would be great.
