### ISSUE TITLE
Absolute paths used for node_modules

### ISSUE THREAD

**Issue by paulyoung** [jmreidy/grunt-browserify#284]
I'm seeing an issue where absolute paths are used in the file produced by browserify for any node modules that are required.

For example, `/Users/[username]/` is present and the file changes depending on who built it. How can I make this relative to the project?

I've tried using `fullPaths: false`. I'm using `^3.2.1`.

**Comment by tleunen** [comment]
Can I see your config? fullPaths is an option inside `browserifyOptions`.
```
options: {
    browserifyOptions : {
        fullPaths: false
```

**Comment by paulyoung** [comment]
I appears that using `./node_modules/grunt-browserify/node_modules/.bin/browserify ...` to build the file uses `"dup"` instead of the full path.

**Comment by paulyoung** [comment]
Config is as follows:
```coffeescript
browserify:
  dist:
    files:
      'dist/gss.js': ['src/gss.coffee']
    options:
      transform: ['coffeeify']
      browserifyOptions:
        extensions: ['.coffee']
        fullPaths: false
```

**Comment by paulyoung** [comment]
OK, weird. It appears to be working now `¯\_(ツ)_/¯`
