### ISSUE TITLE
No string interpolation support?

### ISSUE THREAD

**Issue by calvinchengx** [jmreidy/grunt-browserify#285]
I have the following `Gruntfile.js` and it appears there's no string interpolation support?

```javascript

    // files that our tasks will use
    files: {
      html: {
        src: 'index.html'
      },
      js: {
        vendor: [

        ],
        app: {
          main: ['js/app.js'],
          compiled: 'generated/js/app.min.js'
        }
      }
    },
    // our tasks
    browserify: {
      app: {
        files: {
            '<%= files.js.app.compiled =>': '<%= files.js.app.main =>'  // This does not work.
          //'generated/js/app.min.js': ['js/app.js'],  <-- this works
        }
      },
      options: {
        debug: true
      }
    }
```

I am using `grunt-browserify 3.3.0` and `browserify 8.1.1`.

**Comment by tleunen** [comment]
Hmm I think that's something handle by Grunt. I'll try to reproduce it tonight but in the meantime did you try to use `src` and `dest` instead of `files`?

**Comment by calvinchengx** [comment]
@tleunen I believe I made a typo mistake.

The string interpolation syntax ends with `%>` not `=>`. My bad.  It works as expected. I am sorry for raising an issue that shouldn't be.
