### ISSUE TITLE
A bit confused with factor-bundle and grunt-browserify

### ISSUE THREAD

**Issue by stopachka** [jmreidy/grunt-browserify#286]
Hey everyone, a bit of a noob question -- I'd like to create two bundles -- app_bundle.js, and landing_bundle.js . 

They will both share react, and a few other files, so I thought it would be a good idea to extract those out into a different, common bundle. 

I found factor-bundle, but am having trouble getting it to work. This is what my config looks like for now --

```
    browserify: {
      app: {
        files: {
          '<%= yeoman.tmp %>/scripts/app_bundle.js': ['<%= yeoman.tmp %>/scripts/app.js'],
          '<%= yeoman.tmp %>/scripts/landing_bundle.js': ['<%= yeoman.tmp %>/scripts/landing.js']
        },
        options: {
          watch: true,
          plugin: [
            ['factor-bundle', { o: [ '<%= yeoman.tmp %>/scripts/app_bundle.js', '<%= yeoman.tmp %>/scripts/landing_bundle.js'] }]
          ],
        }
      }
    },
```

I ran it, got no errors, but am not sure where the factored bundle js actually is, I think it didn't actually save anywhere. 

The thing I'm not understanding is, where will factor-bundle save the file? how would I go about specifying that?

**Comment by tleunen** [comment]
The options for `factor-bundle` seem to be: `{ outputs: [ 'bundle/x.js', 'bundle/y.js' ] }`

**Comment by stopachka** [comment]
Het @tleunen, tried, this but am not getting what I expect. 

Currently, landing_bundle.js seems to have nothing in it, and there is no common.js anywhere, I presume it's because I haven't defined it. Any ideas on this?

**Comment by tleunen** [comment]
I never really used factor-bundle so I'm not sure what's wrong in your config. I'll try to build an example and I'll get to you once it's done

**Comment by stopachka** [comment]
Tommy, gratitude! :)

**Comment by tleunen** [comment]
I just added a new [example with factor-bundle](https://github.com/jmreidy/grunt-browserify/blob/master/examples/factor-bundle/Gruntfile.js). Hope it helps :)
Both `browserify-cli` and `grunt-browserify` give the same results.

**Comment by stopachka** [comment]
Works like a charm! Thanks Tommy :)
