### ISSUE TITLE
Seems to me that require('./local_path_to_package_name') does not work ...

### ISSUE THREAD

**Issue by veljkopopovic** [jmreidy/grunt-browserify#291]
I have a npm package on a path ./local_path_to_package_name ... This is a dir with valid package.json and so on. Classic node require('./local_path_to_package_name') returns me what I want to get, but grunt-browserify does not generate proper file. Config for task looks like this:

```javascript
{
  task_name: {
    src:'./local_path_to_package_name'
    dest: 'js/_generated/task_name.js'
  }
}
```

What seemed as problem solution was a patch in grunt-browserify/tasks/browserify.js on line 38:
instead of
```javascript
  var files = grunt.file.expand({filter: 'isFile'}, file.src).map(function (f) {
```
put
```javascript
  var files = grunt.file.expand({}, file.src).map(function (f) {
```

obviously my task was ignored (due to filter record) since my path points to dir not to a file ...

Am I missing something?

**Comment by tleunen** [comment]
Why don't you specify the file path instead of the folder path?

**Comment by veljkopopovic** [comment]
Sorry to bother you, simply did not understand how browserify works ....
