### ISSUE TITLE
preBundleCB gets executed every time watchify rebuilds

### ISSUE THREAD

**Issue by oliverwoodings** [jmreidy/grunt-browserify#298]
When using the preBundleCB and watch option together, the preBundleCB function gets called every time watchify triggers a rebuild. This means you can't use preBundleCB for programmatically registering transforms, plugins, event handlers etc. For example, say I had the following config:
```js
grunt.config("browserify", {
  src: ["foo.js"],
  dest: ["bar.js"],
  options: {
    preBundleCB: function (b) {
      b.transform("fooify");
    },
    browserifyOptions: {
      watch: true,
      keepAlive: true
    }
  }
});
```
If I then do the following:

1. `grunt browserify`
1. Save foo.js
1. Save foo.js

`fooify` will be registered and invoked twice. If you were to register event handlers, they would be invoked twice as well etc. This creates major problems with plugins like cssify, lessify and any other transforms that run language preprocessors on files - if they run twice, they throw parsing errors because they are running on the output of the previous caller.

I understand that by name `preBundleCB` is doing what it is designed to (although I can't quite see what purpose it would have). In reality it seems like what is needed is a 'configure' option - something which [karma-browserify](https://github.com/nikku/karma-browserify#additional-bundle-configuration) have implemented and works well.

**Comment by tleunen** [comment]
I agree, in the case of watchify, `preBundleCB` should only be called once.
Not sure how the `prebundle` event works in karma-browserify though. It seems this event only exist in gulp-browserify and not in the browserify lib.
Anyway, we could easilfy fix it like I said by triggering the callback only once.

**Comment by oliverwoodings** [comment]
Does it not kind of make sense for `preBundleCB` to be triggered each time though? After all, browserify is 'rebundling' each time. I think I prefer the naming convention from karma-browserify of 'configure'.

**Comment by tleunen** [comment]
Hmm.. Good question. I think both could be valid.
After watching your code though, I don't understand why you put the `fooify` transform inside the preBundle callback. That's not something you have to do everytime.

Could you explain exactly what you mean by the configure function? Because from what I see, it's just a shortcut to easily add callback to some events (like preBundle or postBundle). So basically it's the same thing as what we have with `preBundleCB` and `postBundleCB`

**Comment by oliverwoodings** [comment]
The `configure` function would be for programmatically configuring browserify using the API.

If you register an event in preBundle it will experience the same issue with watchify - the event will end up getting bound multiple times.

**Comment by tleunen** [comment]
Got it. You can create a PR for that and I'll merge it ;)

**Comment by oliverwoodings** [comment]
PR ready
