### ISSUE TITLE
Add "files" entry in package.json to ignore everything but listed there

### ISSUE THREAD

**Issue by rubennorte** [jmreidy/grunt-browserify#304]
That way we can save some space, because right now it's including things like the "examples" directory we don't need when installing the package.

More here: https://docs.npmjs.com/files/package.json#files

**Comment by tleunen** [comment]
Is this ok?
```
"files": [
    "lib/",
    "tasks/"
  ],
```

**Comment by rubennorte** [comment]
Yes, although slashes are not necessary
