### ISSUE TITLE
Ability to specify global in transforms

### ISSUE THREAD

**Issue by michaelBenin** [jmreidy/grunt-browserify#312]
Is this possible? If not can we add it in? 

See https://github.com/benbria/aliasify/issues/25

**Comment by tleunen** [comment]
Have you tried
```
options: {
    transform: [{
        aliases: {
            underscore: 'lodash'
        },
        verbose: true,
        global: true
    }, 'aliasify']
}
```

**Comment by michaelBenin** [comment]
With the above config. 

Running "browserify:modern" (browserify) task
Fatal error: Arguments to path.resolve must be strings

Could we reopen this issue?

**Comment by michaelBenin** [comment]
This issue can be solved with:

````
 options: {
        preBundleCB: function (bundle) {
          bundle.transform('aliasify', {
            aliases: {
              'underscore': 'lodash'
            },
            global: true
          });
        }
````

**Comment by michaelBenin** [comment]
I feel like there can be a better way to give options to transforms in the config but this works.

**Comment by tleunen** [comment]
Sorry my example was wrong. Try this
```
options: {
    transform: [
        ['aliasify', {
            aliases: {
                underscore: 'lodash'
            },
            global: true
        }]
    ]
}
```
We'll reopen if this one doesn't work ;)

**Comment by MartijnR** [comment]
I can confirm that @tleunen last example works perfectly. Thanks!
