### ISSUE TITLE
Using alias with browserifyOptions.standalone

### ISSUE THREAD

**Issue by bbraithwaite** [jmreidy/grunt-browserify#313]
I would like to verify the expected behaviour of using alias' in combination with the browserify 'standalone' option.

I have the following config:

``` js
   browserify: {
      client: {
        src: ['index.js'],
        dest: 'build/target.js',
        options: {
          browserifyOptions: {
            standalone: 'myModuleName'
          },
          alias: [
            './lib/custom-module.js:defaultModule',
          ]
        }
      }
    }
```

What I _think_ should happen, is that _target.js_ file will be created, and will be available via 'myModuleName' e.g. window.myModuleName where the object will be the contents of _index.js_. What I am in fact seeing is that _window.myModuleName_ has the contents of the aliased file (./lib/custom-module.js).

Am I missing something with config? I'm happy to work on a fix for this, but wanted to rule out an error with my config first.

**Comment by tleunen** [comment]
Might be related to this bug substack/node-browserify#1163

From what I see, the content of `index.js` is immediately executed and the content of the required files are inside the new 'module' `myModuleName`.

**Comment by bbraithwaite** [comment]
Thanks for pointing me in the right direction. It appears that this is indeed the issue. I'll head over to the node-browserify repo to check on the status of this.

I did put together a workaround which may (or may not!) be of help to others who may read this issue.

I used the aliasify package (_npm install aliasify_). I had to remove the alias option from the grunt file config, which now looks as follows:

``` javascript
browserify: {
      client: {
        src: ['index.js'],
        dest: 'build/target.js',
        options: {
          browserifyOptions: {
            standalone: 'myModuleName'
          }
        }
      }
    }
```

I then added the following to the package.json to use aliasify to handle the module aliasing:

``` json
  "browserify": {
    "transform": [ "aliasify" ]
  },
  "aliasify": {
    "aliases": {
      "defaultModule": "./lib/custom-module.js"
    }
  }
```

This is of course not optimal, since there is now config in the package.json as well as in the grunt file, however it means I can continue to use grunt-browserify until the issue is fixed in node-browserify, at which point I can drop usage of aliasify.

**Comment by jmm** [comment]
@bbraithwaite 
Based on what @tleunen [posted](https://github.com/substack/node-browserify/issues/1163#issuecomment-87520121) it sounds like you're experiencing the issue I discuss in https://github.com/substack/node-browserify/issues/1120#issuecomment-73971126 and https://github.com/substack/node-browserify/issues/968#issuecomment-82356994.

If you want to work around it by aliasing in that kind of fashion, but in the grunt file, you may be able to do it with my [pathmodify](https://www.npmjs.com/package/pathmodify) browserify plugin.

**Comment by bbraithwaite** [comment]
@jmm Thanks for the tip - I'll check it out!
