### ISSUE TITLE
Cannot find module 'browserify-shim' when developing in child directory?

### ISSUE THREAD

**Issue by kopepasah** [jmreidy/grunt-browserify#318]
When running `grunt browserify`, I get the following warning:

```Warning: Cannot find module 'browserify-shim' from '/path-to-project/project'```.

I am wondering if this is because I am developing in a sub directory (e.g. `project/develop`) and, if not, do you have any suggestions of how to fix this issue.

The project in question is [here](https://github.com/juko-labs/han/tree/master/develop).

Any help is appreciated.

**Comment by kopepasah** [comment]
I've run some tests and can confirm that this is an issue. You can see my tests [here](https://github.com/kopepasah/grunt-browserify-test) and can reproduce the issue 100% of the time.

If there is anything I can do to help resolve this, please let me know.

**Comment by tleunen** [comment]
I don't have any issue running your test project... Are you sure you installed all the dependencies?

**Comment by kopepasah** [comment]
I believe so.

From the test repo, this is my output when running `npm install` from `repo/other/develop`.

```
> fsevents@0.3.5 install /Users/koop/Desktop/temp/grunt-browserify-test/other/develop/node_modules/grunt-browserify/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
grunt@0.4.5 node_modules/grunt
├── which@1.0.9
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── nopt@1.0.10 (abbrev@1.0.5)
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)
├── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)

remapify@1.4.3 node_modules/remapify
├── glob@4.5.3 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.4)
├── lodash@2.4.1
└── aliasify@1.7.2 (browserify-transform-tools@1.3.3)

grunt-browserify@3.6.0 node_modules/grunt-browserify
├── async@0.9.0
├── resolve@1.1.6
├── glob@4.5.3 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.4)
├── lodash@3.6.0
└── watchify@2.6.2 (xtend@4.0.0, through2@0.5.1, chokidar@0.12.6)

browserify-shim@3.8.3 node_modules/browserify-shim
├── through@2.3.6
├── mothership@0.2.0 (find-parent-dir@0.3.0)
├── resolve@0.6.3
├── rename-function-calls@0.1.1 (detective@3.1.0)
└── exposify@0.2.0 (transformify@0.1.2, through2@0.4.2, detective@2.3.0)

browserify@9.0.3 node_modules/browserify
├── https-browserify@0.0.0
├── tty-browserify@0.0.0
├── builtins@0.0.7
├── constants-browserify@0.0.1
├── process@0.10.1
├── path-browserify@0.0.0
├── os-browserify@0.1.2
├── inherits@2.0.1
├── isarray@0.0.1
├── commondir@0.0.1
├── string_decoder@0.10.31
├── stream-browserify@1.0.0
├── defined@0.0.0
├── has@1.0.0
├── shell-quote@0.0.1
├── domain-browser@1.1.4
├── xtend@3.0.0
├── shallow-copy@0.0.1
├── duplexer2@0.0.2
├── deep-equal@1.0.0
├── assert@1.3.0
├── querystring-es3@0.2.1
├── timers-browserify@1.4.0
├── punycode@1.2.4
├── through2@1.1.1 (xtend@4.0.0)
├── util@0.10.3
├── events@1.0.2
├── vm-browserify@0.0.4 (indexof@0.0.1)
├── parents@1.0.1 (path-platform@0.11.15)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── concat-stream@1.4.7 (typedarray@0.0.6)
├── http-browserify@1.7.0 (Base64@0.2.1)
├── subarg@1.0.0 (minimist@1.1.1)
├── readable-stream@1.1.13 (core-util-is@1.0.1)
├── url@0.10.3 (punycode@1.3.2, querystring@0.2.0)
├── shasum@1.0.1 (sha.js@2.3.6, json-stable-stringify@0.0.1)
├── labeled-stream-splicer@1.0.2 (stream-splicer@1.3.1)
├── buffer@3.1.2 (ieee754@1.1.4, is-array@1.0.1, base64-js@0.0.8)
├── browser-resolve@1.8.2
├── resolve@1.1.6
├── glob@4.5.3 (once@1.3.1, inflight@1.0.4, minimatch@2.0.4)
├── JSONStream@0.10.0 (through@2.3.6, jsonparse@0.0.5)
├── deps-sort@1.3.5 (minimist@0.2.0, through2@0.5.1, JSONStream@0.8.4)
├── browserify-zlib@0.1.4 (pako@0.2.6)
├── crypto-browserify@3.9.13 (randombytes@2.0.1, create-hmac@1.1.3, pbkdf2-compat@3.0.2, create-hash@1.1.1, browserify-aes@1.0.0, create-ecdh@2.0.0, diffie-hellman@3.0.1, browserify-sign@2.8.0, public-encrypt@2.0.0)
├── browser-pack@4.0.1 (umd@3.0.0, through2@0.5.1, JSONStream@0.8.4, combine-source-map@0.3.0)
├── insert-module-globals@6.2.1 (process@0.6.0, through@2.3.6, JSONStream@0.7.4, combine-source-map@0.3.0, lexical-scope@1.1.0)
├── syntax-error@1.1.2 (acorn@0.9.0)
└── module-deps@3.7.3 (xtend@4.0.0, minimist@0.2.0, subarg@0.0.1, through2@0.4.2, stream-combiner2@1.0.2, JSONStream@0.7.4, detective@4.0.0)
```

It is the same output when running from the `repo/standard` directory.

---

Then after running `grunt browserify` (from `repo/other/develop` I get the following warning:

```
Running "browserify:dist" (browserify) task
>> Error: Unable to find a browserify-shim config section in the package.json for /Users/koop/Desktop/temp/grunt-browserify-test/other/js/test.js while parsing file: /Users/koop/Desktop/temp/grunt-browserify-test/other/js/test.js
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

I get no errors from the `repo/standard` directory.

**Comment by tleunen** [comment]
First of all, `browserify-shim` only uses the configuration from the package.json file. So you can remove the transformation in your gruntfile.

Doing this will resolve the issue `Unable to find a browserify-shim config section in the package.json`. Browserify cannot find the configuration because he's searching it from `other/js` directory, which of course doesn't have any package.json file. I don't know why he's doing that though.

This is not a `grunt-browserify` issue. You could easily reproduce it with browserify cli.
`browserify ../js/test.js -t browserify-shim -o ../js/build/test.js`

The only thing `grunt-browserify` could do is warn the user to remove `browserify-shim` from the transform array in the gruntfile.

**Comment by kopepasah** [comment]
@tleunen thanks for following up so quickly. I did a bit of research and just found [this](https://github.com/thlorenz/browserify-shim/issues/61), I think it is what you mentioned. I will continue my discussion there.

Thanks for the help!

**Comment by tleunen** [comment]
From the author @thlorenz on the thread you mentioned:

>I had a look and believe the reason for this failing is that hmm.js is outside of the project (i.e. the app which contains the package.json).
>The correct setup is to have all your files inside (or below) the dir that contains the package.json.

So yes, your js directory is outside of the develop directory (main app directory), and this is what causes the error.

**Comment by kopepasah** [comment]
@tleunen you mentioned:

> First of all, browserify-shim only uses the configuration from the package.json file. So you can remove the transformation in your grunt file.

I am just curious why the transform is not required in the grunt file. Does running `grunt browserify` automatically run `browserify-shim`?

**Comment by tleunen** [comment]
Because of this: [substack/node-browserify#packagejson](https://github.com/substack/node-browserify#packagejson).

Browserify will read `package.json`. And `browserify-shim` is only compatible with a configuration in `package.json`. That's why you had to remove it from the gruntfile.

**Comment by kopepasah** [comment]
Thanks for the help @tleunen.
