### ISSUE TITLE
Configure browserify transform for npm installed react modules

### ISSUE THREAD

**Issue by Braynid** [jmreidy/grunt-browserify#321]
I'm writing a React app and would like to require a react module in my code (react-autocomplete).

I've setup grunt-browserify together with grunt-react to transform jsx to js for browserify as follows:

        browserify: {
            build: {
                options: {
                    transform: [require('grunt-react').browserify]
                },
                files: {
                    src: [ 'js_src/app.js'],
                    dest: 'resources/js/app.js'
                }
            }
        }

This works great for my code but when I require react-autocomplete I get an `Unexpected token` error within react-autocomplete right where the first `<div>` jsx element appears in the code. This makes me think grunt-react isn't parsing react-autocomplete to js.

It's worth mentioning that I've installed react-autocomplete via `npm install` and it resides in node_modules, if that makes a difference.

The question is, how do I configure grunt-browserify so that it also parses other react modules?

I'm currently using:
├──  browserify@9.0.8
├── grunt@0.4.5
├── grunt-browserify@3.7.0
├── grunt-react@0.12.1
└── react-autocomplete@0.0.2

**Comment by tleunen** [comment]
Transforms only applies to local modules by default, but you should be able to run the transform on global modules as well using the `global` option.

```
    browserify: {
        build: {
            options: {
                transform: [
                    [require('grunt-react').browserify, {global: true}]
                ]
            },
            files: {
                src: [ 'js_src/app.js'],
                dest: 'resources/js/app.js'
            }
        }
    }
```

**Comment by Braynid** [comment]
That did the trick. Thanks!

I saw the --global-transform flag in the browserify documentation but couldn't get it to work from Grunt.
