### ISSUE TITLE
How to export a library?

### ISSUE THREAD

**Issue by piranna** [jmreidy/grunt-browserify#324]
By using ```alias```, you can be able to define some files that will be available to be ```require()```d by other code, problem is that this can't be done for the main ```export```. It's said, if you define an alias for the same file you have defined as the src of your target, grunt-browserify will fail saying it can't be able to find that file. It somewhat has some sense since there's no reference to the module, but how I can be able to do it? A hack that works is to define as src a dumb browser file that only export the real library export while the alias point to this real one, but it's a really nasty hack.

And no, by default It doesn't work to use ```require()```, and no, I don't want to use standalone, because this is for a plugin system I'm doing and using standalone pollutes the global namespace.

**Comment by tleunen** [comment]
What are you trying to achieve? Because it seems this is why `standalone` exists, but you don't want to use it.

**Comment by piranna** [comment]
No, ```standalone``` add a new element to the global namespace (window), but what I want instead is to be able to ```require()``` it from another module... Seems this is not feasable in its current status...

**Comment by tleunen** [comment]
Hmm I don't understand. If you want to require it, don't use browserify and use directly your main file.

**Comment by piranna** [comment]
I want to require it in the browser... As I told you this is a plugin mechanism, where I have [a central element](https://github.com/Kurento/kurento-client-bower) and some [third-party provided modules](https://github.com/kurento?utf8=%E2%9C%93&query=module).

**Comment by tleunen** [comment]
Ok then you should be able to just create your bundle by only using `require` with an exposed name.

**Comment by piranna** [comment]
But if I remove it from ```src```, will it do the requires expansion?

**Comment by tleunen** [comment]
Yep, you can easily create a bundle without anything in `src`. It's often used when you have to create a `lib` bundle. And it seems that's what you are trying to achieve.

**Comment by piranna** [comment]
Yes, this is mostly what I'm trying to achieve, I'll try to give it a chance :-)
