### ISSUE TITLE
Loading "browserify.js" tasks...ERROR - Error: Cannot find module 'browserify'

### ISSUE THREAD

**Issue by foxx** [jmreidy/grunt-browserify#325]
Okay, I've managed to narrow down this problem, after almost a day of debugging.

I'm able to reproduce this error when doing this;

```
$ npm install browserify
$ npm install grunt-browserify
$ grunt
Loading "browserify.js" tasks...ERROR
Error: Cannot find module 'browserify'
```

It goes away if I do this instead;

```
$ npm install grunt-browserify
$ npm install browserify
$ grunt
```

So for whatever reason, these two packages are somehow colliding with each other or causing some dependancy hell, and the order in which you install them determines whether it will fail or not. And because npm doesn't sort `dependancies/devDependancies` in the order which you specified, you can't control this. Currently my fix is to manually install browserify after dev deps, but this isn't very clean.

I don't know enough about the npm installs to fully understand why this is happening, but I can safely say this is a bug.

This was also raised in #241, [lineman-browserify#14][1], [lineman-browserify#15][2].

My versions are;

```
NVM_VERSION=v0.17.3
NODE_VERSION=0.10.32
grunt-browserify^3.7.0
```

Possibly a problem with resolve-dep?

[1]: https://github.com/linemanjs/lineman-browserify/issues/14
[2]: https://github.com/linemanjs/lineman-browserify/issues/15

**Comment by tleunen** [comment]
Weird.. Because `grunt-browserify` uses the latest version of `browserify`. Is it the only 2 dependencies you have?
Could you setup a small test case to reproduce it?

**Comment by foxx** [comment]
Sure, here you go.

Initially I was unable to reproduce the problem, but I realised our builds used a symlink for pointing `node_modules` to `/tmp` to prevent npm installing into Vagrant shared folders. Once I added the symlink, the problem comes back.

I've trawled npm source and documentation, as well as google, to see if symlinks are discouraged or known to cause problems, but found nothing to suggest this. Other popular grunt tasks seem to cope with this fine, so I'm tempted to say this is still a bug within `grunt-browserify`.

### Works

```
$ npm install
$ grunt
```

### Breaks

```
$ ln -sv `mktemp -d` node_modules
$ npm install
$ grunt
Loading "browserify.js" tasks...ERROR
>> Error: Cannot find module 'browserify'
Warning: Task "browserify" not found. Use --force to continue.
Error: Task "browserify" not found.
    at Task.run (/tmp/tmp.CRGT6jq7HD/grunt/lib/util/task.js:179:28)
    at Object.thisTask.fn (/tmp/tmp.CRGT6jq7HD/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/tmp/tmp.CRGT6jq7HD/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/tmp/tmp.CRGT6jq7HD/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/tmp/tmp.CRGT6jq7HD/grunt/lib/util/task.js:300:12)
    at Task.start (/tmp/tmp.CRGT6jq7HD/grunt/lib/util/task.js:309:5)
    at Object.grunt.tasks (/tmp/tmp.CRGT6jq7HD/grunt/lib/grunt.js:164:8)
    at Object.module.exports [as cli] (/tmp/tmp.CRGT6jq7HD/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/home/vagrant/.nvm/versions/node/v0.12.2/lib/node_modules/grunt-cli/bin/grunt:45:20)
    at Module._compile (module.js:460:26)
```

I did some debugging in [util/task.js](https://github.com/gruntjs/grunt/blob/v0.4.5/lib/util/task.js#L175) and dumped the contents of `things`. As you can see, when a symlink is present, things.task is undefined and only has 2 elements, where as without a symlink it has 3.

My guess is that `grunt-browserify` is doing things in a different way than other modules, and thus causing the problem, rather than a bug within `grunt` itself, though I could be wrong.

### Without symlink;

```
[ { task:
     { name: 'default',
       info: 'Alias for "browserify" task.',
       fn: [Function],
       meta: [Object] },
    nameArgs: 'default',
    args: [],
    flags: {} } ]
[ { task:
     { name: 'browserify',
       info: 'Grunt task for browserify.',
       fn: [Function],
       meta: [Object],
       multi: true },
    nameArgs: 'browserify',
    args: [],
    flags: {} } ]
[ { task:
     { name: 'browserify',
       info: 'Grunt task for browserify.',
       fn: [Function],
       meta: [Object],
       multi: true },
    nameArgs: 'browserify:all',
    args: [ 'all' ],
    flags: { all: true } } ]
```

### With symlink

```
[ { task:
     { name: 'default',
       info: 'Alias for "browserify" task.',
       fn: [Function],
       meta: [Object] },
    nameArgs: 'default',
    args: [],
    flags: {} } ]
[ { task: undefined,
    nameArgs: 'browserify',
    args: [ 'browserify' ],
    flags: { browserify: true } } ]
```

Here are the test case files

### package.json

```js
{
  "name": "test",
  "version": "1.0.0",
  "devDependencies": {
    "browserify": "^9.0.8",
    "grunt": "^0.4.5",
    "grunt-browserify": "^3.7.0",
    "grunt-cli": "^0.1.13",
    "load-grunt-tasks": "^3.1.0"
  }
}
```

### Gruntfile.js

```js
module.exports = function (grunt) {
  require('load-grunt-tasks')(grunt);

  grunt.initConfig({
    browserify: {
      all: {
        files: {
          'public/static/app.js': ['js/main.js']
        },
        options: {

        }
      }
    }
  });
  grunt.registerTask('default', ['browserify']);
};
```

**Comment by foxx** [comment]
Also ran into another issue, if I install the `glob` package then I get the following error;

```
Loading "browserify.js" tasks...ERROR
>> Error: Cannot find module 'glob'
>>     at Function.Module._resolveFilename (module.js:336:15)
>>     at Function.Module._load (module.js:278:25)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (/tmp/tmp.2rdtawQqfK/grunt-browserify/lib/runner.js:4:12)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
```

Once I remove it from dependancies, the error goes away. And like before, if I install it after I've ran `npm install`, the problem also goes away.

**Comment by foxx** [comment]
Sadly I decided not to carry on using grunt, for completely different reasons. However I ran into this same problem with other libraries, again caused by symlinks, and was able to fix it by using `NODE_PATH`, for example;

```
NODE_PATH=`pwd`/node_modules grunt
```

Hopefully this may help others in the future, closing for now.
