### ISSUE TITLE
factor-bundle example is creating empty outputs

### ISSUE THREAD

**Issue by damcard** [jmreidy/grunt-browserify#330]
I did a clone of the project, npm install in the root and in the examples/factor-bundle dir. When I run grunt in the factor-bundle example, the x.js and y.js in public only contains ''require=". When I run the command 'browserify client/x.js client/y.js -p [ factor-bundle -o public/x.js -o publicy.js ] -o public/common.js' it works fine.  I cannot figure out why it does not work through grunt.  Any help is appreciated.

**Comment by damcard** [comment]
After updating node/npm, this issue seem to go away.

**Comment by justinjmoses** [comment]
Ugh - getting the same thing - factor-bundle is somehow being interrupted before it finishes writing the output. Sometimes `require=` and sometimes a full line ending with an open brace. Works fine with browserify-cli but not with grunt-browserify. Reproduced to have no options. @damcard which version of node did you end up on?
