### ISSUE TITLE
Dependency (ReactJS) fatally double-loaded

### ISSUE THREAD

**Issue by Shriken** [jmreidy/grunt-browserify#335]
Hi folks,

I'm having an issue where ReactJS is being loaded twice from one module. This causes a fatal error in React: "Invariant Violation: React.render(): Invalid component element. This may be caused by unintentionally loading two independent copies of React."

I have two .js files which both need to require React. Now, normally I might try to find a way around that, but I've found that switching the order of the chunks in browserify's output bundle solves the error. Unfortunately I'm not aware of any configuration option that allows me to dictate the order to grunt-browserify.

I know that browserify has gotten the order "right" in [this example here](https://github.com/DavidWells/isomorphic-react-example). Note that they used gulp to build.

Am I doing something wrong, or is this a bug?
Thanks!

**Comment by tleunen** [comment]
Yeah this can happen with browserify... See this https://github.com/substack/node-browserify/issues/1181

**Comment by giggio** [comment]
I have found that [browserify-resolutions](https://github.com/Updater/browserify-resolutions) solves the problem. I had the same problem with jquery plugins, I had one instance for each jquery called by each plugin. browserify-resolutions fixed it.

**Comment by tleunen** [comment]
Thanks @giggio. Deduping the modules resolves the issue, so I'll close this.
