### ISSUE TITLE
Cannot read property of indexOf

### ISSUE THREAD

**Issue by garygreen** [jmreidy/grunt-browserify#337]
How would you create a series of options which allows for the below command (with `-r` option)?

```
browserify -r ./lang/ru.js > dist/lang/ru.js
```

What I got so far:

```javascript
browserify: {
	ruLang: {
		options: {
			require: ['lang/ru.js']
		},
		dest: 'dist/lang/ru.js'
	}
}
```

This produces error: `Cannot read property of indexOf`

**Comment by tleunen** [comment]
`require` should be an array.

**Comment by ezmiller** [comment]
I am getting the same error with the following: 

```
    vendor: {
      dest: '.tmp/public/js/dependencies/vendor.js',
      options: {
        debug: false,
        require: [
          'react',
          'react/addons',
          'react-router',
          'jquery',
          'backbone'
        ]
      }
    } 
```

**Comment by garygreen** [comment]
Still same issue with array.

**Comment by ezmiller** [comment]
@garygreen doesn't [] denote an array? could you give a quick example of what you mean just to eliminate any ambiguity.

**Comment by garygreen** [comment]
@ezmiller I've updated code in original issue. I was expecting that to work but it produces same error. I suspect internally browserify is trying to find the `files` object and getting nothing?

**Comment by ezmiller** [comment]
@garygreen You mean you expected your code in the [original comment](https://github.com/jmreidy/grunt-browserify/issues/337#issue-87020260) above to work? I'm a bit confused. What code did you update?

**Comment by garygreen** [comment]
@ezmiller yes.... You can see the command I am trying to reproduce in the original comment:

```
browserify -r ./lang/ru.js > dist/lang/ru.js
```

I believe my options as in my original comment should produce a command like the above, but it doesn't seem to work. Internally I think grunt-browserify requires a `files` and it's not finding it, so erroring. The `files` isn't applicable in that above command so not sure it's even possible....

**Comment by ezmiller** [comment]
Right, well okay then you are having the same problem that I am having. Up until now, I'd only been able to import files in this way by referencing the specific path in `node_modules` like so:

```
 vendor: {
      src: [
          './node_modules/react/reactjs'
      ]
      dest: '.tmp/public/js/dependencies/vendor.js',
      options: {
        debug: false,
      }
    }

**Comment by tleunen** [comment]
This is actually related to this issue https://github.com/jmreidy/grunt-browserify/issues/334
You currently have to provide a `src`. Put it as an empty array and it should be fine.
