### ISSUE TITLE
Upgrade of major version of Browserify on 3.9.0

### ISSUE THREAD

**Issue by Myztiq** [jmreidy/grunt-browserify#342]
When you upgraded from Browserify 10.x.x to 11.x.x that constitutes a breaking change. The release should have been 4.0.0 not 3.9.0.

This broke our builds and was somewhat tricky to track down.

A side-note, the changelog is also missing the update.

**Comment by tleunen** [comment]
Sorry about that, I published it earlier to make a fix for something but it was too fast I guess... I just unpublished it so it won't create any issues for others users starting now, and I'll publish 4.0 with the upgrade.

Thanks for letting us know about it

**Comment by Myztiq** [comment]
Thank you for the quick turnaround!
