### ISSUE TITLE
Browserify errors aren't verbose

### ISSUE THREAD

**Issue by mightyiam** [jmreidy/grunt-browserify#357]
When browserify has an error I don't get enough info. I get this:
![screenshot_2015-09-20_00-23-21](https://cloud.githubusercontent.com/assets/635591/9978235/f3043686-5f2d-11e5-99c3-506dc9f0a2fa.png)

I would like to get the same as with running browserify directly:
![screenshot_2015-09-20_00-23-38](https://cloud.githubusercontent.com/assets/635591/9978238/07281786-5f2e-11e5-81d0-14e15575d881.png)

**Comment by mightyiam** [comment]
Oh, boy. That's actually not what I was thinking. I didn't even look at the output from direct `browserify`. It doesn't really help me figure out where the erroneous `require` call is.

**Comment by DirtyHairy** [comment]
I can't see where browserify is showing more information than the grunt plugin. I am closing this issue for now, feel free to reopen if there is still an issue for you.
