### ISSUE TITLE
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

### ISSUE THREAD

**Issue by chapterjason** [jmreidy/grunt-browserify#359]
I get this warning and the bundeling dont work

my package.json:
```
{
  [...]
  "devDependencies": {
    "grunt": "0.4.5",
    "grunt-browserify": "4.0.1"
  }
  [...]
}
```
my Gruntfile:
```
module.exports = function (grunt) {

    grunt.loadNpmTasks('grunt-browserify');

    grunt.initConfig({
        browserify: {
            dist: {
                files: {
                    'main.js': ['./source/**/*.js']
                }
            }
        },
    });
    grunt.registerTask('browserify', ['browserify']);
};
```

**Comment by DirtyHairy** [comment]
Is this still an issue? If yes: what are the node and grunt versions involved?

**Comment by chapterjason** [comment]
@DirtyHairy ohh, long time a go. I looked forward for another solution to work with browserify. I remember there was a weird warning, but I stopped working with grunt.

**Comment by DirtyHairy** [comment]
:smile: Sounds more like an issue involving specific versions of grunt, browserify and node rather than a problem with `grunt-browserify` to me anyway. Closing...
