### ISSUE TITLE
[discuss] why does the tranform take an array?

### ISSUE THREAD

**Issue by deostroll** [jmreidy/grunt-browserify#368]
Just wanted to know the rationale behind why the browserify config have the transform property as an array. 

I've seen most gulp examples where the browserify workflow goes like this:

```javascript
gulp.task('build', function(){
  return browserify({
    entries: 'app/es6/main.js',
    debug: true
  })
  .transform(babelify)
  .on('error', gutil.log)
  .bundle()
  .on('error', gutil.log)
  .pipe(source('./main.js'))
  .pipe(gulp.dest('./app/scripts/'))
});
```
My thought is that the api is _meant_ to be used _that_ way. It feels unnecessary array-fying it and sending that to the plugin.

**Comment by DirtyHairy** [comment]
Choices, plus the fact that you use the array to specify a transform chain, something that you'd do using multiple transform calls on browserify if you're using gulp :smirk:
