### ISSUE TITLE
Not stubbing "fs" module?

### ISSUE THREAD

**Issue by simonlovesyou** [jmreidy/grunt-browserify#373]
Using:
```
grunt-browserify: ^4.0.1
grunt: ^0.4.5
grunt-cli: v0.1.13
browserify: 11.2.0
```
I can compile my files correctly with browserify with 
``
browserify index.js -o dist/index.js --exclude lapack 
``
which will stub out the fs module correctly, but when I use grunt-browserify with 
```
browserify: {
   extension: {
      options: {
          exclude: ['lapack'],
      },
      files: {
        'modules/js/bundle.js': ['./index.js'']
      }
  }
},
```
I get 
``
Uncaught Error: Cannot find module 'fs'
``
in the browser. I've tried these settings as well to specifically declare I don't want any builtins:

```
...
browserifyOptions: {
  'no-builtins': true
},
...
```

but no difference. 

Am I just missing something?

**Comment by DirtyHairy** [comment]
Hi Simon!

Stubbing out `fs` works just fine for me. Does the issue still persist?

Cheers
    -Christian

**Comment by simonlovesyou** [comment]
Hey Christian,

Yeah, it's fine now. I'm gonna go ahead and close this issue.

Thanks!
