### ISSUE TITLE
Release with browserify ^12+

### ISSUE THREAD

**Issue by jwhitfieldseed** [jmreidy/grunt-browserify#375]
Browserify@11 has an [issue with transforms on symlinked files](https://github.com/substack/node-browserify/pull/1365) - in my case transformed symlinked dependencies have incorrect source maps.

Is it possible to release with a bumped browserify version?

* [12.x release notes](https://github.com/substack/node-browserify/blob/master/changelog.markdown#1202)
* [13.x release notes](https://github.com/substack/node-browserify/blob/master/changelog.markdown#1300)

**Comment by tleunen** [comment]
version 5.0 with browserify 13
