### ISSUE TITLE
Handling errors not working with Babel

### ISSUE THREAD

**Issue by jonathandion** [jmreidy/grunt-browserify#376]
Hi, 
It's possible to handle import/export errors with babel?

example :

import myModule from '../module/myModule.js';
Error : Unexpected token (15:0) while parsing file.

I would like to keep my task alive.

There is my config : 

```
options: {
    transform: [
        'babelify',
        'browserify-shim',
        "browserify-global-shim"
    ],
    watch: true,
    keepAlive: true,
    browserifyOptions: {
        debug: true
    }
}
```

Thanks.

**Comment by justsml** [comment]
Sounds like I have the same issue...
```sh
...
blah/blah/blah/index.jade:1
>> include ../../mixins.jade
>>          ^
>> ParseError: Unexpected token
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```
I am suddenly dealing with broken transforms. My app uses jadeify - and apparently it's not working.

I've been passing options in from my `Gruntfile.js` with (few) problems for over 2 years.
Now after moving to a new PC, and running a clean `npm install` - my build fails. Seems like options aren't being used - and to make things more painful, there is no clear way to know what is actually going on, or what options have been applied (is there a use for `debug: true`?)

Debugging grunt issues is hard enough as it is... :cry: 

After `grunting` for a few hours, I tried adding config to my `package.json` and that seemed to give me different errors:

> As you can see, I just started throwing shit at the problem...

```js
// from package.json
  "browserify": {
    "fullPaths": true,
    "noParse":  [ "angular", "L", "moment", "lodash", "jquery" ],
    "exclude":  [ "angular", "L", "moment", "lodash", "jquery" ],
    "external": [ "angular", "L", "moment", "lodash", "jquery" ],
    "ignore":   [ "angular", "L", "moment", "lodash", "jquery" ],
    "debug": true, // why???
    "keepAlive": true,
    "transform": [
      ["jadeify"],
      ["babelify", {
        "ignore": [
          "/data/",
          "/node_modules/",
          "/bower_components/",
          "/county-state-data/",
          "/app-tools/"
        ],
        "sourceMaps": true,
        "presets": ["stage-0", "es2015"]
      }],
      ["debowerify"]
    ]
  },
```


![](http://res.cloudinary.com/ddd/image/upload/v1441143886/panda-rampage__tumblr_nq7srwTXqr1stn6klo1_500_gm2som.gif)


Any help/suggestions appreciated!

Thanks in advance!

**Comment by DirtyHairy** [comment]
@Jonathan: What does your .babelrc look like?

@Daniel: This sounds like a problem with the order of the transforms. Make sure that `babelify` is first in the array; otherwise, `jadeify` will choke on ES6 module syntax.

**Comment by DirtyHairy** [comment]
Closing, please reopen if you still have issues,
