### ISSUE TITLE
Ability to specify a custom logger

### ISSUE THREAD

**Issue by fatfisz** [jmreidy/grunt-browserify#382]
A simple option that allows replacing the default `grunt` logger with something else would do. Would it be ok?

**Comment by DirtyHairy** [comment]
Hi Rafał!

What exactly are you trying to achieve, and what API for specifying another logger do you suggest?

Cheers
    -Christian

**Comment by fatfisz** [comment]
Hi, I don't remember now :/ I'll close this and reopen when I come back to the issue!
