### ISSUE TITLE
messy code with Chinese characters in source maps

### ISSUE THREAD

**Issue by jaylone** [jmreidy/grunt-browserify#384]
It seems that lastest version depend on inline-source-map@0.5.0, like this:
![image](https://cloud.githubusercontent.com/assets/8166444/19924493/1c29cb16-a127-11e6-8723-c32e0e37620c.png);

but charset in inline-source-map@0.5.0 was not correct. In inline-source-map@0.6.0 use `charset=` instead of `charset:`, like this:
```
Generator.prototype.inlineMappingUrl = function () {
  var charset = this.opts.charset || 'utf-8';
  return '//# sourceMappingURL=data:application/json;charset=' + charset + ';base64,' + this.base64Encode();
};
```
[Here is inline-source-map issue](https://github.com/thlorenz/inline-source-map/issues/6)
could you upgrade the version of browserify?
thanks.

**Comment by DirtyHairy** [comment]
Hi @jaylone !

`browserify` is referenced in package.json as `"browserify": "^13.0.0"`. As `browserify` is currently at version 13.1.1, the latest version of `browserify` is already pulled in by `grunt-browserify`. Is there anything else to be done here?

Cheers
-Christian

**Comment by jaylone** [comment]
Thank you for reply. It work as expected now.
