### ISSUE TITLE
Edge Issue with stream-http

### ISSUE THREAD

**Issue by ecoslado** [jmreidy/grunt-browserify#385]
Hi we've recently detected and fixed an issue in Microsoft Edge 35. http library didn't perform any request.

browserify included the change, but we work with the grunt wrapper. could you include it please?

The PR I'm talking about:
https://github.com/jhiesey/stream-http/pull/54

The issue in node-browserify:
https://github.com/substack/node-browserify/issues/1644

**Comment by DirtyHairy** [comment]
Hi @ecoslado !

`browserify` is referenced in package.json as `"browserify": "^13.0.0"`. As `browserify` is currently at version 13.1.1, the latest version of `browserify` is already pulled in by `grunt-browserify`. Is there anything else to be done here?

Cheers
-Christian

**Comment by ecoslado** [comment]
hi, thanks a lot. I missed the ^ :S So I close it.
