### ISSUE TITLE
Multiple Browserify tasks

### ISSUE THREAD

**Issue by thecodejack** [jmreidy/grunt-browserify#388]
I need to run multiple browserify tasks as I have two outputs with different options in same projects. I tried running with below but it didn't work. Any plans to support for same?

```
browserify: {
bundle1: {
   options: {
        "transform": [
          [
            "babelify",
            {
              "presets": [
                "es2015",
                "react",
                "stage-0"
              ]
            }
          ]
        ],
        browserifyOptions: {
          debug: true,
          extensions: ['.js', '.jsx'],,
          entries: ['file1', 'file2']
        }
      },
      dist: {
        files: {
          'output1': ['file1'],
          'output2': ['file1']
        }
      }
},
bundle2: {
    options: {
        "transform": [
          [
            "babelify",
            {
              "presets": [
                "es2015",
                "react",
                "stage-0"
              ]
            }
          ]
        ],
        browserifyOptions: {
          debug: true,
          extensions: ['.js', '.jsx'],,
          entries: ['file3', 'file4']
        }
      },
      dist: {
        files: {
          'output3': ['output2'],
          'output4': ['file5']
        }
      }
}
}
```

**Comment by DirtyHairy** [comment]
Hi @thecodejack !

Can give a bit more detail? Multiple configurations are definitely supported, and many projects use this.

Cheers
    -Christian

**Comment by thecodejack** [comment]
Hi @DirtyHairy ! Thanks for quick response. 

If you see above json, I have made two sub tasks bundle1 & bundle2. Both have been given different options & dist. What I am expecting this to work when I run following commands
`grunt browserify`
`grunt browserify:bundle1`
`grunt browserify:bundle2`

When I run above 3 commands, nothing is happening.

**Comment by DirtyHairy** [comment]
Looking at your config, the way you wrap the `files` object with `dist` seems strange and is definitely wrong. Can you retry without the wrapper?

**Comment by thecodejack** [comment]
Sorry for late response. This got resolved. Thanks.
