### ISSUE TITLE
browserifyOptions mapping unclear

### ISSUE THREAD

**Issue by mflux** [jmreidy/grunt-browserify#391]
I've only figured out two working browserifyOptions by reading stackoverflow posts

  standalone
  debug

The readme links to https://github.com/substack/node-browserify#usage

However what are they, in JSON?

For example I want to use the option:

    --no-browser-field

What is it supposed to look like in the options?

        browserifyOptions: {
          nobrowserfield: true
        }

That doesn't seem to work. Should one include the dashes, or no dashes? Are they supposed to be camel-case? Is there a list of options that are ported over?

**Comment by fabianTMC** [comment]
Same here. This needs to be elaborated better.

**Comment by DirtyHairy** [comment]
There is no mapping; `browserifyOptions` is directly passed to the browserify API. If you need further documentation, you'll have to look at browserify itself. I agree that the browserify docs are lacking in this respect, but there is nothing grunt-browserify can do about this.

From a superficial glance at the browserify source, suppose that the option @mflux is looking for is `browserField: false`, but I'd have to try it out to be sure.
