### ISSUE TITLE
Unable to specify plugin/transform order

### ISSUE THREAD

**Issue by HerringtonDarkholme** [jmreidy/grunt-browserify#393]
I'm using tsify(https://github.com/TypeStrong/tsify) and brfs(https://github.com/substack/brfs).

I have this error:

> SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

This error is related to loading order.

> Make sure that if you're using the API, your setup .plugin('tsify') is done before any transforms such as .transform('babelify'). tsify needs to run first!

However, grunt-browserify will always load transform first, not plugin.

https://github.com/jmreidy/grunt-browserify/blob/master/lib/runner.js#L99-L109

**Comment by DirtyHairy** [comment]
If you want to deviate from grunt-browserify's default order, you can specify a function that configures the browserify bundle via `configure`. For reference, the corresponding part of the Gruntfile in one of my own projects looks like this:

```
            stellerator_prod: {
                dest: 'web/js/compiled/stellerator.prod.js',
                src: ['src/web/stella/stellerator/main.tsx'],
                options: {
                    configure: b => b
                        .plugin('tsify', {project: __dirname})
                        .transform(envify({
                            NODE_ENV: 'production'
                        }), {global: true})
                        .transform('brfs'),
                    browserifyOptions: {
                        debug: true
                    }
                }
            }
```
