### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by rubensayshi** [jmreidy/grunt-browserify#395]
Hey,

I'm wondering if there's gonna be a release tagged soon with the update to the latest browserify (already in master), because the current 5.0.0 version still uses browserify 13.x

**Comment by DirtyHairy** [comment]
Good point, thanks for the reminder :smirk: @tleunen , could you grant me the necessary permissions on NPM for doing a new release?

**Comment by tleunen** [comment]
@DirtyHairy Sure, could you tell me what's your npm login?

cc @jmreidy

**Comment by DirtyHairy** [comment]
@tleunen Thanks alot, my login is dirtyhairy

**Comment by tleunen** [comment]
@DirtyHairy done :)

**Comment by DirtyHairy** [comment]
@tleunen Thanks alot! I'm off keyboard until next monday and will do the release once I'm back :smirk:

**Comment by DirtyHairy** [comment]
Release 5.1.0 is out on NPM.

**Comment by RinkAttendant6** [comment]
Can you release 5.2.0 on npm as well? I was looking at the new incremental build feature in 5.2.0 and took me a little while to realize that the latest version on npm is only 5.1.0.

**Comment by DirtyHairy** [comment]
Will do :smirk:

**Comment by DirtyHairy** [comment]
5.2.0 is published on NPM.
