### ISSUE TITLE
5.2.1 Release for Browserify Update

### ISSUE THREAD

**Issue by bartboy011** [jmreidy/grunt-browserify#403]
Hey all,

I was curious what the timeline looked like to release the next version that includes the `browserify` version bump to `16.x`? There are a handful of ES2018 features covered in v16.x of Browserify that are currently breaking in my build due to the v14.x requirement.

**Comment by DirtyHairy** [comment]
It is in my pipeline, I just need a bit of time for testing to make sure that there are no regressions. I'll try to find time tonight.

**Comment by bartboy011** [comment]
@DirtyHairy Thanks! Let me know if I can help with that process.

**Comment by DirtyHairy** [comment]
A small update: sorry, the week turned out to be too busy, I'll publish the update this weekend.

**Comment by DirtyHairy** [comment]
Done. I have released the update as 5.3.0.

**Comment by bartboy011** [comment]
@DirtyHairy Thank you!
